# Generated by Django 2.0 on 2019-12-03 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miembro', '0002_cuentasporcobrar_saldo_cc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembro',
            name='foto_m',
        ),
    ]
