# Generated by Django 2.0 on 2019-12-03 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_auto_20190114_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='imagen_articulo',
        ),
    ]
